///////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 1.3
//  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
//  /   /         Filename : s6_gtp.v
// /___/   /\     Timestamp :
// \   \  /  \
//  \___\/\___\
//
//
// Module S6_GTP (a GTP Wrapper)
// Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard
//
//
// (c) Copyright 2009 Xilinx, Inc. All rights reserved.
//
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
//
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of,
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.



`timescale 1ns / 1ps


//***************************** Entity Declaration ****************************
(* CORE_GENERATION_INFO = "S6_GTP,s6_gtpwizard_v1_3,{gtp0_protocol_file=Start_from_scratch,gtp1_protocol_file=Use_GTP0_settings}" *)
module S6_GTP #
  (
   // Simulation attributes
   parameter   WRAPPER_SIM_GTPRESET_SPEEDUP    = 0,    // Set to 1 to speed up sim reset
   parameter   WRAPPER_SIMULATION              = 0     // Set to 1 for simulation
   )
   (

    //_________________________________________________________________________
    //_________________________________________________________________________
    //TILE0  (X0_Y0)

    //------------------------------- PLL Ports --------------------------------
    input         TILE0_CLK00_IN,
    input         TILE0_CLK01_IN,
    input         TILE0_GTPRESET0_IN,
    input         TILE0_GTPRESET1_IN,
    output        TILE0_PLLLKDET0_OUT,
    output        TILE0_PLLLKDET1_OUT,
    output        TILE0_REFCLKOUT0_OUT,
    output        TILE0_REFCLKOUT1_OUT,
    output        TILE0_RESETDONE0_OUT,
    output        TILE0_RESETDONE1_OUT,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output [3:0]  TILE0_RXCHARISK0_OUT,
    output [3:0]  TILE0_RXCHARISK1_OUT,
    output [3:0]  TILE0_RXDISPERR0_OUT,
    output [3:0]  TILE0_RXDISPERR1_OUT,
    output [3:0]  TILE0_RXNOTINTABLE0_OUT,
    output [3:0]  TILE0_RXNOTINTABLE1_OUT,
    output [3:0]  TILE0_RXRUNDISP0_OUT,
    output [3:0]  TILE0_RXRUNDISP1_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    input         TILE0_RXENMCOMMAALIGN0_IN,
    input         TILE0_RXENMCOMMAALIGN1_IN,
    input         TILE0_RXENPCOMMAALIGN0_IN,
    input         TILE0_RXENPCOMMAALIGN1_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output [31:0] TILE0_RXDATA0_OUT,
    output [31:0] TILE0_RXDATA1_OUT,
    output        TILE0_RXRECCLK0_OUT,
    output        TILE0_RXRECCLK1_OUT,
    input         TILE0_RXRESET0_IN,
    input         TILE0_RXRESET1_IN,
    input         TILE0_RXCDRRESET0_IN,
    input         TILE0_RXCDRRESET1_IN,
    input         TILE0_RXUSRCLK0_IN,
    input         TILE0_RXUSRCLK1_IN,
    input         TILE0_RXUSRCLK20_IN,
    input         TILE0_RXUSRCLK21_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input         TILE0_GATERXELECIDLE0_IN,
    input         TILE0_GATERXELECIDLE1_IN,
    input         TILE0_IGNORESIGDET0_IN,
    input         TILE0_IGNORESIGDET1_IN,
    output        TILE0_RXELECIDLE0_OUT,
    output        TILE0_RXELECIDLE1_OUT,
    input [1:0]   TILE0_RXEQMIX0_IN,
    input [1:0]   TILE0_RXEQMIX1_IN,
    input         TILE0_RXN0_IN,
    input         TILE0_RXN1_IN,
    input         TILE0_RXP0_IN,
    input         TILE0_RXP1_IN,
    //--------- Receive Ports - RX Elastic Buffer and Phase Alignment ----------
    input         TILE0_RXENPMAPHASEALIGN0_IN,
    input         TILE0_RXENPMAPHASEALIGN1_IN,
    input         TILE0_RXPMASETPHASE0_IN,
    input         TILE0_RXPMASETPHASE1_IN,
    output [2:0]  TILE0_RXSTATUS0_OUT,
    output [2:0]  TILE0_RXSTATUS1_OUT,
    //------------- Receive Ports - RX Loss-of-sync State Machine --------------
    output [1:0]  TILE0_RXLOSSOFSYNC0_OUT,
    output [1:0]  TILE0_RXLOSSOFSYNC1_OUT,
    //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
    input [7:0]   TILE0_DADDR_IN,
    input         TILE0_DCLK_IN,
    input         TILE0_DEN_IN,
    input [15:0]  TILE0_DI_IN,
    output        TILE0_DRDY_OUT,
    output [15:0] TILE0_DRPDO_OUT,
    input         TILE0_DWE_IN,
    //-------------------------- TX/RX Datapath Ports --------------------------
    output [1:0]  TILE0_GTPCLKFBEAST_OUT,
    output [1:0]  TILE0_GTPCLKFBWEST_OUT,
    output [1:0]  TILE0_GTPCLKOUT0_OUT,
    output [1:0]  TILE0_GTPCLKOUT1_OUT,
    //----------------- Transmit Ports - 8b10b Encoder Control -----------------
    input [3:0]   TILE0_TXCHARISK0_IN,
    input [3:0]   TILE0_TXCHARISK1_IN,
    //------------- Transmit Ports - TX Buffer and Phase Alignment -------------
    output [1:0]  TILE0_TXBUFSTATUS0_OUT,
    output [1:0]  TILE0_TXBUFSTATUS1_OUT,
    input         TILE0_TXENPMAPHASEALIGN0_IN,
    input         TILE0_TXENPMAPHASEALIGN1_IN,
    input         TILE0_TXPMASETPHASE0_IN,
    input         TILE0_TXPMASETPHASE1_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input [31:0]  TILE0_TXDATA0_IN,
    input [31:0]  TILE0_TXDATA1_IN,
    input         TILE0_TXRESET0_IN,
    input         TILE0_TXRESET1_IN,
    input         TILE0_TXUSRCLK0_IN,
    input         TILE0_TXUSRCLK1_IN,
    input         TILE0_TXUSRCLK20_IN,
    input         TILE0_TXUSRCLK21_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input [3:0]   TILE0_TXDIFFCTRL0_IN,
    input [3:0]   TILE0_TXDIFFCTRL1_IN,
    output        TILE0_TXN0_OUT,
    output        TILE0_TXN1_OUT,
    output        TILE0_TXP0_OUT,
    output        TILE0_TXP1_OUT,
    input [2:0]   TILE0_TXPREEMPHASIS0_IN,
    input [2:0]   TILE0_TXPREEMPHASIS1_IN,
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    input         TILE0_TXELECIDLE0_IN,
    input         TILE0_TXELECIDLE1_IN,
    //------------------- Transmit Ports - TX Ports for SATA -------------------
    input         TILE0_TXCOMSTART0_IN,
    input         TILE0_TXCOMSTART1_IN,
    input         TILE0_TXCOMTYPE0_IN,
    input         TILE0_TXCOMTYPE1_IN,



    //_________________________________________________________________________
    //_________________________________________________________________________
    //TILE1  (X1_Y0)

    //------------------------------- PLL Ports --------------------------------
    input         TILE1_CLK00_IN,
    input         TILE1_CLK01_IN,
    input         TILE1_GTPRESET0_IN,
    input         TILE1_GTPRESET1_IN,
    output        TILE1_PLLLKDET0_OUT,
    output        TILE1_PLLLKDET1_OUT,
    output        TILE1_REFCLKOUT0_OUT,
    output        TILE1_REFCLKOUT1_OUT,
    output        TILE1_RESETDONE0_OUT,
    output        TILE1_RESETDONE1_OUT,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output [3:0]  TILE1_RXCHARISK0_OUT,
    output [3:0]  TILE1_RXCHARISK1_OUT,
    output [3:0]  TILE1_RXDISPERR0_OUT,
    output [3:0]  TILE1_RXDISPERR1_OUT,
    output [3:0]  TILE1_RXNOTINTABLE0_OUT,
    output [3:0]  TILE1_RXNOTINTABLE1_OUT,
    output [3:0]  TILE1_RXRUNDISP0_OUT,
    output [3:0]  TILE1_RXRUNDISP1_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    input         TILE1_RXENMCOMMAALIGN0_IN,
    input         TILE1_RXENMCOMMAALIGN1_IN,
    input         TILE1_RXENPCOMMAALIGN0_IN,
    input         TILE1_RXENPCOMMAALIGN1_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output [31:0] TILE1_RXDATA0_OUT,
    output [31:0] TILE1_RXDATA1_OUT,
    output        TILE1_RXRECCLK0_OUT,
    output        TILE1_RXRECCLK1_OUT,
    input         TILE1_RXRESET0_IN,
    input         TILE1_RXRESET1_IN,
    input         TILE1_RXCDRRESET0_IN,
    input         TILE1_RXCDRRESET1_IN,
    input         TILE1_RXUSRCLK0_IN,
    input         TILE1_RXUSRCLK1_IN,
    input         TILE1_RXUSRCLK20_IN,
    input         TILE1_RXUSRCLK21_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input         TILE1_GATERXELECIDLE0_IN,
    input         TILE1_GATERXELECIDLE1_IN,
    input         TILE1_IGNORESIGDET0_IN,
    input         TILE1_IGNORESIGDET1_IN,
    output        TILE1_RXELECIDLE0_OUT,
    output        TILE1_RXELECIDLE1_OUT,
    input [1:0]   TILE1_RXEQMIX0_IN,
    input [1:0]   TILE1_RXEQMIX1_IN,
    input         TILE1_RXN0_IN,
    input         TILE1_RXN1_IN,
    input         TILE1_RXP0_IN,
    input         TILE1_RXP1_IN,
    //--------- Receive Ports - RX Elastic Buffer and Phase Alignment ----------
    input         TILE1_RXENPMAPHASEALIGN0_IN,
    input         TILE1_RXENPMAPHASEALIGN1_IN,
    input         TILE1_RXPMASETPHASE0_IN,
    input         TILE1_RXPMASETPHASE1_IN,
    output [2:0]  TILE1_RXSTATUS0_OUT,
    output [2:0]  TILE1_RXSTATUS1_OUT,
    //------------- Receive Ports - RX Loss-of-sync State Machine --------------
    output [1:0]  TILE1_RXLOSSOFSYNC0_OUT,
    output [1:0]  TILE1_RXLOSSOFSYNC1_OUT,
    //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
    input [7:0]   TILE1_DADDR_IN,
    input         TILE1_DCLK_IN,
    input         TILE1_DEN_IN,
    input [15:0]  TILE1_DI_IN,
    output        TILE1_DRDY_OUT,
    output [15:0] TILE1_DRPDO_OUT,
    input         TILE1_DWE_IN,
    //-------------------------- TX/RX Datapath Ports --------------------------
    output [1:0]  TILE1_GTPCLKFBEAST_OUT,
    output [1:0]  TILE1_GTPCLKFBWEST_OUT,
    output [1:0]  TILE1_GTPCLKOUT0_OUT,
    output [1:0]  TILE1_GTPCLKOUT1_OUT,
    //----------------- Transmit Ports - 8b10b Encoder Control -----------------
    input [3:0]   TILE1_TXCHARISK0_IN,
    input [3:0]   TILE1_TXCHARISK1_IN,
    //------------- Transmit Ports - TX Buffer and Phase Alignment -------------
    output [1:0]  TILE1_TXBUFSTATUS0_OUT,
    output [1:0]  TILE1_TXBUFSTATUS1_OUT,
    input         TILE1_TXENPMAPHASEALIGN0_IN,
    input         TILE1_TXENPMAPHASEALIGN1_IN,
    input         TILE1_TXPMASETPHASE0_IN,
    input         TILE1_TXPMASETPHASE1_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input [31:0]  TILE1_TXDATA0_IN,
    input [31:0]  TILE1_TXDATA1_IN,
    input         TILE1_TXRESET0_IN,
    input         TILE1_TXRESET1_IN,
    input         TILE1_TXUSRCLK0_IN,
    input         TILE1_TXUSRCLK1_IN,
    input         TILE1_TXUSRCLK20_IN,
    input         TILE1_TXUSRCLK21_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input [3:0]   TILE1_TXDIFFCTRL0_IN,
    input [3:0]   TILE1_TXDIFFCTRL1_IN,
    output        TILE1_TXN0_OUT,
    output        TILE1_TXN1_OUT,
    output        TILE1_TXP0_OUT,
    output        TILE1_TXP1_OUT,
    input [2:0]   TILE1_TXPREEMPHASIS0_IN,
    input [2:0]   TILE1_TXPREEMPHASIS1_IN,
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    input         TILE1_TXELECIDLE0_IN,
    input         TILE1_TXELECIDLE1_IN,
    //------------------- Transmit Ports - TX Ports for SATA -------------------
    input         TILE1_TXCOMSTART0_IN,
    input         TILE1_TXCOMSTART1_IN,
    input         TILE1_TXCOMTYPE0_IN,
    input         TILE1_TXCOMTYPE1_IN


    );


   //***************************** Wire Declarations *****************************

   // ground and vcc signals
   wire           tied_to_ground_i;
   wire [63:0]    tied_to_ground_vec_i;
   wire           tied_to_vcc_i;
   wire [63:0]    tied_to_vcc_vec_i;
   wire           tile0_plllkdet0_i;
   wire           tile0_plllkdet1_i;
   wire           tile1_plllkdet0_i;
   wire           tile1_plllkdet1_i;

   reg            tile0_plllkdet0_i2;
   reg            tile0_plllkdet1_i2;
   reg            tile1_plllkdet0_i2;
   reg            tile1_plllkdet1_i2;


   //********************************* Main Body of Code**************************

   assign tied_to_ground_i             = 1'b0;
   assign tied_to_ground_vec_i         = 64'h0000000000000000;
   assign tied_to_vcc_i                = 1'b1;
   assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;

   generate
      if (WRAPPER_SIMULATION==1)
        begin : simulation

           assign TILE0_PLLLKDET0_OUT = tile0_plllkdet0_i2;
           assign TILE0_PLLLKDET1_OUT = tile0_plllkdet1_i2;
           assign TILE1_PLLLKDET0_OUT = tile1_plllkdet0_i2;
           assign TILE1_PLLLKDET1_OUT = tile1_plllkdet1_i2;


           always@(tile0_plllkdet0_i)
             begin
                if (tile0_plllkdet0_i) begin
                   #100
                     tile0_plllkdet0_i2 <= tile0_plllkdet0_i;
                end
                else
                  begin
                     tile0_plllkdet0_i2 <= tile0_plllkdet0_i;
                  end
             end

           always@(tile0_plllkdet1_i)
             begin
                if (tile0_plllkdet1_i) begin
                   #100
                     tile0_plllkdet1_i2 <= tile0_plllkdet1_i;
                end
                else
                  begin
                     tile0_plllkdet1_i2 <= tile0_plllkdet1_i;
                  end
             end

           always@(tile1_plllkdet0_i)
             begin
                if (tile1_plllkdet0_i) begin
                   #100
                     tile1_plllkdet0_i2 <= tile1_plllkdet0_i;
                end
                else
                  begin
                     tile1_plllkdet0_i2 <= tile1_plllkdet0_i;
                  end
             end

           always@(tile1_plllkdet1_i)
             begin
                if (tile1_plllkdet1_i) begin
                   #100
                     tile1_plllkdet1_i2 <= tile1_plllkdet1_i;
                end
                else
                  begin
                     tile1_plllkdet1_i2 <= tile1_plllkdet1_i;
                  end
             end


        end //end WRAPPER_SIMULATION =1 generate section
      else
        begin: implementation

           assign TILE0_PLLLKDET0_OUT = tile0_plllkdet0_i;
           assign TILE0_PLLLKDET1_OUT = tile0_plllkdet1_i;
           assign TILE1_PLLLKDET0_OUT = tile1_plllkdet0_i;
           assign TILE1_PLLLKDET1_OUT = tile1_plllkdet1_i;


        end
   endgenerate //End generate for WRAPPER_SIMULATION

   //------------------------- Tile Instances  -------------------------------



   //_________________________________________________________________________
   //_________________________________________________________________________
   //TILE0  (X0_Y0)

   S6_GTP_TILE #
     (
      // Simulation attributes
      .TILE_SIM_GTPRESET_SPEEDUP   (WRAPPER_SIM_GTPRESET_SPEEDUP),

      //
      .TILE_CLKINDC_B_0                ("TRUE"),
      .TILE_CLKINDC_B_1                ("TRUE"),
      //
      .TILE_PLL_SOURCE_0               ("PLL0"),
      .TILE_PLL_SOURCE_1               ("PLL1")
      )
   tile0_s6_gtp_i
     (
      //------------------------------- PLL Ports --------------------------------
      .CLK00_IN                       (TILE0_CLK00_IN),
      .CLK01_IN                       (TILE0_CLK01_IN),
      .GTPRESET0_IN                   (TILE0_GTPRESET0_IN),
      .GTPRESET1_IN                   (TILE0_GTPRESET1_IN),
      .PLLLKDET0_OUT                  (tile0_plllkdet0_i),
      .PLLLKDET1_OUT                  (tile0_plllkdet1_i),
      .REFCLKOUT0_OUT                 (TILE0_REFCLKOUT0_OUT),
      .REFCLKOUT1_OUT                 (TILE0_REFCLKOUT1_OUT),
      .RESETDONE0_OUT                 (TILE0_RESETDONE0_OUT),
      .RESETDONE1_OUT                 (TILE0_RESETDONE1_OUT),
      //--------------------- Receive Ports - 8b10b Decoder ----------------------
      .RXCHARISK0_OUT                 (TILE0_RXCHARISK0_OUT),
      .RXCHARISK1_OUT                 (TILE0_RXCHARISK1_OUT),
      .RXDISPERR0_OUT                 (TILE0_RXDISPERR0_OUT),
      .RXDISPERR1_OUT                 (TILE0_RXDISPERR1_OUT),
      .RXNOTINTABLE0_OUT              (TILE0_RXNOTINTABLE0_OUT),
      .RXNOTINTABLE1_OUT              (TILE0_RXNOTINTABLE1_OUT),
      .RXRUNDISP0_OUT                 (TILE0_RXRUNDISP0_OUT),
      .RXRUNDISP1_OUT                 (TILE0_RXRUNDISP1_OUT),
      //------------- Receive Ports - Comma Detection and Alignment --------------
      .RXENMCOMMAALIGN0_IN            (TILE0_RXENMCOMMAALIGN0_IN),
      .RXENMCOMMAALIGN1_IN            (TILE0_RXENMCOMMAALIGN1_IN),
      .RXENPCOMMAALIGN0_IN            (TILE0_RXENPCOMMAALIGN0_IN),
      .RXENPCOMMAALIGN1_IN            (TILE0_RXENPCOMMAALIGN1_IN),
      //----------------- Receive Ports - RX Data Path interface -----------------
      .RXDATA0_OUT                    (TILE0_RXDATA0_OUT),
      .RXDATA1_OUT                    (TILE0_RXDATA1_OUT),
      .RXRECCLK0_OUT                  (TILE0_RXRECCLK0_OUT),
      .RXRECCLK1_OUT                  (TILE0_RXRECCLK1_OUT),
      .RXRESET0_IN                    (TILE0_RXRESET0_IN),
      .RXRESET1_IN                    (TILE0_RXRESET1_IN),
      .RXCDRRESET0_IN                    (TILE0_RXCDRRESET0_IN),
      .RXCDRRESET1_IN                    (TILE0_RXCDRRESET1_IN),
      .RXUSRCLK0_IN                   (TILE0_RXUSRCLK0_IN),
      .RXUSRCLK1_IN                   (TILE0_RXUSRCLK1_IN),
      .RXUSRCLK20_IN                  (TILE0_RXUSRCLK20_IN),
      .RXUSRCLK21_IN                  (TILE0_RXUSRCLK21_IN),
      //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
      .GATERXELECIDLE0_IN             (TILE0_GATERXELECIDLE0_IN),
      .GATERXELECIDLE1_IN             (TILE0_GATERXELECIDLE1_IN),
      .IGNORESIGDET0_IN               (TILE0_IGNORESIGDET0_IN),
      .IGNORESIGDET1_IN               (TILE0_IGNORESIGDET1_IN),
      .RXELECIDLE0_OUT                (TILE0_RXELECIDLE0_OUT),
      .RXELECIDLE1_OUT                (TILE0_RXELECIDLE1_OUT),
      .RXEQMIX0_IN                    (TILE0_RXEQMIX0_IN),
      .RXEQMIX1_IN                    (TILE0_RXEQMIX1_IN),
      .RXN0_IN                        (TILE0_RXN0_IN),
      .RXN1_IN                        (TILE0_RXN1_IN),
      .RXP0_IN                        (TILE0_RXP0_IN),
      .RXP1_IN                        (TILE0_RXP1_IN),
      //--------- Receive Ports - RX Elastic Buffer and Phase Alignment ----------
      .RXENPMAPHASEALIGN0_IN          (TILE0_RXENPMAPHASEALIGN0_IN),
      .RXENPMAPHASEALIGN1_IN          (TILE0_RXENPMAPHASEALIGN1_IN),
      .RXPMASETPHASE0_IN              (TILE0_RXPMASETPHASE0_IN),
      .RXPMASETPHASE1_IN              (TILE0_RXPMASETPHASE1_IN),
      .RXSTATUS0_OUT                  (TILE0_RXSTATUS0_OUT),
      .RXSTATUS1_OUT                  (TILE0_RXSTATUS1_OUT),
      //------------- Receive Ports - RX Loss-of-sync State Machine --------------
      .RXLOSSOFSYNC0_OUT              (TILE0_RXLOSSOFSYNC0_OUT),
      .RXLOSSOFSYNC1_OUT              (TILE0_RXLOSSOFSYNC1_OUT),
      //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
      .DADDR_IN                       (TILE0_DADDR_IN),
      .DCLK_IN                        (TILE0_DCLK_IN),
      .DEN_IN                         (TILE0_DEN_IN),
      .DI_IN                          (TILE0_DI_IN),
      .DRDY_OUT                       (TILE0_DRDY_OUT),
      .DRPDO_OUT                      (TILE0_DRPDO_OUT),
      .DWE_IN                         (TILE0_DWE_IN),
      //-------------------------- TX/RX Datapath Ports --------------------------
      .GTPCLKFBEAST_OUT               (TILE0_GTPCLKFBEAST_OUT),
      .GTPCLKFBWEST_OUT               (TILE0_GTPCLKFBWEST_OUT),
      .GTPCLKOUT0_OUT                 (TILE0_GTPCLKOUT0_OUT),
      .GTPCLKOUT1_OUT                 (TILE0_GTPCLKOUT1_OUT),
      //----------------- Transmit Ports - 8b10b Encoder Control -----------------
      .TXCHARISK0_IN                  (TILE0_TXCHARISK0_IN),
      .TXCHARISK1_IN                  (TILE0_TXCHARISK1_IN),
      //------------- Transmit Ports - TX Buffer and Phase Alignment -------------
      .TXBUFSTATUS0_OUT               (TILE0_TXBUFSTATUS0_OUT),
      .TXBUFSTATUS1_OUT               (TILE0_TXBUFSTATUS1_OUT),
      .TXENPMAPHASEALIGN0_IN          (TILE0_TXENPMAPHASEALIGN0_IN),
      .TXENPMAPHASEALIGN1_IN          (TILE0_TXENPMAPHASEALIGN1_IN),
      .TXPMASETPHASE0_IN              (TILE0_TXPMASETPHASE0_IN),
      .TXPMASETPHASE1_IN              (TILE0_TXPMASETPHASE1_IN),
      //---------------- Transmit Ports - TX Data Path interface -----------------
      .TXDATA0_IN                     (TILE0_TXDATA0_IN),
      .TXDATA1_IN                     (TILE0_TXDATA1_IN),
      .TXRESET0_IN                    (TILE0_TXRESET0_IN),
      .TXRESET1_IN                    (TILE0_TXRESET1_IN),
      .TXUSRCLK0_IN                   (TILE0_TXUSRCLK0_IN),
      .TXUSRCLK1_IN                   (TILE0_TXUSRCLK1_IN),
      .TXUSRCLK20_IN                  (TILE0_TXUSRCLK20_IN),
      .TXUSRCLK21_IN                  (TILE0_TXUSRCLK21_IN),
      //------------- Transmit Ports - TX Driver and OOB signalling --------------
      .TXDIFFCTRL0_IN                 (TILE0_TXDIFFCTRL0_IN),
      .TXDIFFCTRL1_IN                 (TILE0_TXDIFFCTRL1_IN),
      .TXN0_OUT                       (TILE0_TXN0_OUT),
      .TXN1_OUT                       (TILE0_TXN1_OUT),
      .TXP0_OUT                       (TILE0_TXP0_OUT),
      .TXP1_OUT                       (TILE0_TXP1_OUT),
      .TXPREEMPHASIS0_IN              (TILE0_TXPREEMPHASIS0_IN),
      .TXPREEMPHASIS1_IN              (TILE0_TXPREEMPHASIS1_IN),
      //--------------- Transmit Ports - TX Ports for PCI Express ----------------
      .TXELECIDLE0_IN                 (TILE0_TXELECIDLE0_IN),
      .TXELECIDLE1_IN                 (TILE0_TXELECIDLE1_IN),
      //------------------- Transmit Ports - TX Ports for SATA -------------------
      .TXCOMSTART0_IN                 (TILE0_TXCOMSTART0_IN),
      .TXCOMSTART1_IN                 (TILE0_TXCOMSTART1_IN),
      .TXCOMTYPE0_IN                  (TILE0_TXCOMTYPE0_IN),
      .TXCOMTYPE1_IN                  (TILE0_TXCOMTYPE1_IN)

      );



   //_________________________________________________________________________
   //_________________________________________________________________________
   //TILE1  (X1_Y0)

   S6_GTP_TILE #
     (
      // Simulation attributes
      .TILE_SIM_GTPRESET_SPEEDUP   (WRAPPER_SIM_GTPRESET_SPEEDUP),

      //
      .TILE_CLKINDC_B_0                ("TRUE"),
      .TILE_CLKINDC_B_1                ("TRUE"),
      //
      .TILE_PLL_SOURCE_0               ("PLL0"),
      .TILE_PLL_SOURCE_1               ("PLL1")
      )
   tile1_s6_gtp_i
     (
      //------------------------------- PLL Ports --------------------------------
      .CLK00_IN                       (TILE1_CLK00_IN),
      .CLK01_IN                       (TILE1_CLK01_IN),
      .GTPRESET0_IN                   (TILE1_GTPRESET0_IN),
      .GTPRESET1_IN                   (TILE1_GTPRESET1_IN),
      .PLLLKDET0_OUT                  (tile1_plllkdet0_i),
      .PLLLKDET1_OUT                  (tile1_plllkdet1_i),
      .REFCLKOUT0_OUT                 (TILE1_REFCLKOUT0_OUT),
      .REFCLKOUT1_OUT                 (TILE1_REFCLKOUT1_OUT),
      .RESETDONE0_OUT                 (TILE1_RESETDONE0_OUT),
      .RESETDONE1_OUT                 (TILE1_RESETDONE1_OUT),
      //--------------------- Receive Ports - 8b10b Decoder ----------------------
      .RXCHARISK0_OUT                 (TILE1_RXCHARISK0_OUT),
      .RXCHARISK1_OUT                 (TILE1_RXCHARISK1_OUT),
      .RXDISPERR0_OUT                 (TILE1_RXDISPERR0_OUT),
      .RXDISPERR1_OUT                 (TILE1_RXDISPERR1_OUT),
      .RXNOTINTABLE0_OUT              (TILE1_RXNOTINTABLE0_OUT),
      .RXNOTINTABLE1_OUT              (TILE1_RXNOTINTABLE1_OUT),
      .RXRUNDISP0_OUT                 (TILE1_RXRUNDISP0_OUT),
      .RXRUNDISP1_OUT                 (TILE1_RXRUNDISP1_OUT),
      //------------- Receive Ports - Comma Detection and Alignment --------------
      .RXENMCOMMAALIGN0_IN            (TILE1_RXENMCOMMAALIGN0_IN),
      .RXENMCOMMAALIGN1_IN            (TILE1_RXENMCOMMAALIGN1_IN),
      .RXENPCOMMAALIGN0_IN            (TILE1_RXENPCOMMAALIGN0_IN),
      .RXENPCOMMAALIGN1_IN            (TILE1_RXENPCOMMAALIGN1_IN),
      //----------------- Receive Ports - RX Data Path interface -----------------
      .RXDATA0_OUT                    (TILE1_RXDATA0_OUT),
      .RXDATA1_OUT                    (TILE1_RXDATA1_OUT),
      .RXRECCLK0_OUT                  (TILE1_RXRECCLK0_OUT),
      .RXRECCLK1_OUT                  (TILE1_RXRECCLK1_OUT),
      .RXRESET0_IN                    (TILE1_RXRESET0_IN),
      .RXRESET1_IN                    (TILE1_RXRESET1_IN),
      .RXCDRRESET0_IN                    (TILE1_RXCDRRESET0_IN),
      .RXCDRRESET1_IN                    (TILE1_RXCDRRESET1_IN),
      .RXUSRCLK0_IN                   (TILE1_RXUSRCLK0_IN),
      .RXUSRCLK1_IN                   (TILE1_RXUSRCLK1_IN),
      .RXUSRCLK20_IN                  (TILE1_RXUSRCLK20_IN),
      .RXUSRCLK21_IN                  (TILE1_RXUSRCLK21_IN),
      //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
      .GATERXELECIDLE0_IN             (TILE1_GATERXELECIDLE0_IN),
      .GATERXELECIDLE1_IN             (TILE1_GATERXELECIDLE1_IN),
      .IGNORESIGDET0_IN               (TILE1_IGNORESIGDET0_IN),
      .IGNORESIGDET1_IN               (TILE1_IGNORESIGDET1_IN),
      .RXELECIDLE0_OUT                (TILE1_RXELECIDLE0_OUT),
      .RXELECIDLE1_OUT                (TILE1_RXELECIDLE1_OUT),
      .RXEQMIX0_IN                    (TILE1_RXEQMIX0_IN),
      .RXEQMIX1_IN                    (TILE1_RXEQMIX1_IN),
      .RXN0_IN                        (TILE1_RXN0_IN),
      .RXN1_IN                        (TILE1_RXN1_IN),
      .RXP0_IN                        (TILE1_RXP0_IN),
      .RXP1_IN                        (TILE1_RXP1_IN),
      //--------- Receive Ports - RX Elastic Buffer and Phase Alignment ----------
      .RXENPMAPHASEALIGN0_IN          (TILE1_RXENPMAPHASEALIGN0_IN),
      .RXENPMAPHASEALIGN1_IN          (TILE1_RXENPMAPHASEALIGN1_IN),
      .RXPMASETPHASE0_IN              (TILE1_RXPMASETPHASE0_IN),
      .RXPMASETPHASE1_IN              (TILE1_RXPMASETPHASE1_IN),
      .RXSTATUS0_OUT                  (TILE1_RXSTATUS0_OUT),
      .RXSTATUS1_OUT                  (TILE1_RXSTATUS1_OUT),
      //------------- Receive Ports - RX Loss-of-sync State Machine --------------
      .RXLOSSOFSYNC0_OUT              (TILE1_RXLOSSOFSYNC0_OUT),
      .RXLOSSOFSYNC1_OUT              (TILE1_RXLOSSOFSYNC1_OUT),
      //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
      .DADDR_IN                       (TILE1_DADDR_IN),
      .DCLK_IN                        (TILE1_DCLK_IN),
      .DEN_IN                         (TILE1_DEN_IN),
      .DI_IN                          (TILE1_DI_IN),
      .DRDY_OUT                       (TILE1_DRDY_OUT),
      .DRPDO_OUT                      (TILE1_DRPDO_OUT),
      .DWE_IN                         (TILE1_DWE_IN),
      //-------------------------- TX/RX Datapath Ports --------------------------
      .GTPCLKFBEAST_OUT               (TILE1_GTPCLKFBEAST_OUT),
      .GTPCLKFBWEST_OUT               (TILE1_GTPCLKFBWEST_OUT),
      .GTPCLKOUT0_OUT                 (TILE1_GTPCLKOUT0_OUT),
      .GTPCLKOUT1_OUT                 (TILE1_GTPCLKOUT1_OUT),
      //----------------- Transmit Ports - 8b10b Encoder Control -----------------
      .TXCHARISK0_IN                  (TILE1_TXCHARISK0_IN),
      .TXCHARISK1_IN                  (TILE1_TXCHARISK1_IN),
      //------------- Transmit Ports - TX Buffer and Phase Alignment -------------
      .TXBUFSTATUS0_OUT               (TILE1_TXBUFSTATUS0_OUT),
      .TXBUFSTATUS1_OUT               (TILE1_TXBUFSTATUS1_OUT),
      .TXENPMAPHASEALIGN0_IN          (TILE1_TXENPMAPHASEALIGN0_IN),
      .TXENPMAPHASEALIGN1_IN          (TILE1_TXENPMAPHASEALIGN1_IN),
      .TXPMASETPHASE0_IN              (TILE1_TXPMASETPHASE0_IN),
      .TXPMASETPHASE1_IN              (TILE1_TXPMASETPHASE1_IN),
      //---------------- Transmit Ports - TX Data Path interface -----------------
      .TXDATA0_IN                     (TILE1_TXDATA0_IN),
      .TXDATA1_IN                     (TILE1_TXDATA1_IN),
      .TXRESET0_IN                    (TILE1_TXRESET0_IN),
      .TXRESET1_IN                    (TILE1_TXRESET1_IN),
      .TXUSRCLK0_IN                   (TILE1_TXUSRCLK0_IN),
      .TXUSRCLK1_IN                   (TILE1_TXUSRCLK1_IN),
      .TXUSRCLK20_IN                  (TILE1_TXUSRCLK20_IN),
      .TXUSRCLK21_IN                  (TILE1_TXUSRCLK21_IN),
      //------------- Transmit Ports - TX Driver and OOB signalling --------------
      .TXDIFFCTRL0_IN                 (TILE1_TXDIFFCTRL0_IN),
      .TXDIFFCTRL1_IN                 (TILE1_TXDIFFCTRL1_IN),
      .TXN0_OUT                       (TILE1_TXN0_OUT),
      .TXN1_OUT                       (TILE1_TXN1_OUT),
      .TXP0_OUT                       (TILE1_TXP0_OUT),
      .TXP1_OUT                       (TILE1_TXP1_OUT),
      .TXPREEMPHASIS0_IN              (TILE1_TXPREEMPHASIS0_IN),
      .TXPREEMPHASIS1_IN              (TILE1_TXPREEMPHASIS1_IN),
      //--------------- Transmit Ports - TX Ports for PCI Express ----------------
      .TXELECIDLE0_IN                 (TILE1_TXELECIDLE0_IN),
      .TXELECIDLE1_IN                 (TILE1_TXELECIDLE1_IN),
      //------------------- Transmit Ports - TX Ports for SATA -------------------
      .TXCOMSTART0_IN                 (TILE1_TXCOMSTART0_IN),
      .TXCOMSTART1_IN                 (TILE1_TXCOMSTART1_IN),
      .TXCOMTYPE0_IN                  (TILE1_TXCOMTYPE0_IN),
      .TXCOMTYPE1_IN                  (TILE1_TXCOMTYPE1_IN)

      );



endmodule

